spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reading_challenge
    username: alian # TODO 민감 정보이므로 오픈하지 않도록 수정이 필요함.
    password: 1234

    jpa:
      open-in-view: false
      defer-datasource-initialization: true
      hibernate.ddl-auto: create
      show-sql: true
      properties:
        hibernate.format_sql: true
        hibernate.default_batch_fetch_size: 100
    sql.init.mode: always